#--------------------------------------
# GitHub Action Part-1 - Basics
# 
# Copyleft (c) Danny Diemiekhin 2022.
#--------------------------------------
name: My-GitHubActions-Basics

on:
  push:
    branches: 
      - master 

jobs:
  my_testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Print Hello Message
      run : Echo "Hello World from Testing job"
      
      
  my_deploy:
    runs-on: ubunty-latest
    steps:
    - name: Print Hello Message
      run : Echo "Hello World from Deploy job"
